# fly.toml app configuration file generated for t3-clone-elixir on 2025-06-10T09:19:22+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 't3-clone-elixir'
PRIMARY_REGION = "sin"
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = "bin/t3_clone_elixir eval \"T3CloneElixir.Release.create_and_migrate()\""

[env]
  PHX_HOST = 't3-clone-elixir.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
